# Generated by Django 3.1.2 on 2022-10-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=30)),
                ('Short_Description', models.CharField(max_length=50)),
                ('is_veg', models.BooleanField()),
                ('is_bestseller', models.BooleanField()),
                ('is_available', models.BooleanField()),
                ('Price', models.FloatField()),
                ('Category', models.CharField(max_length=50)),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
