# Generated by Django 3.2.12 on 2022-11-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Edit_Items', '0008_auto_20221031_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
