# Generated by Django 3.1.2 on 2022-10-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Edit_Items', '0002_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_link',
            field=models.URLField(default='https://us.123rf.com/450wm/tele52/tele521811/tele52181100001/113575054-vector-green-salad-icon-includes-red-and-orange-tomato-lettuce-cheese-egg-red-bell-pepper-croutons-a.jpg?ver=6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
