# Generated by Django 3.2.12 on 2022-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Edit_Items', '0003_auto_20221029_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_link',
            field=models.URLField(default='<a href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXfmEz-c80qt9LMDJbbw2uRu0t3ajDZ6xcyQ&usqp=CAU"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXfmEz-c80qt9LMDJbbw2uRu0t3ajDZ6xcyQ&usqp=CAU" alt="PBM" border="0"></a> '),
        ),
    ]
