# Generated by Django 3.1.2 on 2022-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Edit_Items', '0004_auto_20221029_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
