# Generated by Django 3.2.12 on 2022-10-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Edit_Items', '0006_alter_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Category',
        ),
    ]
